# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
  - master

pool:
  vmImage: "ubuntu-latest"

variables:
  solution: "AspNetCoreSpa.sln"
  buildPlatform: "Any CPU"
  buildConfiguration: "Release"

steps:
  - task: NuGetToolInstaller@1
    displayName: Install Nuget

  - task: UseDotNet@2
    displayName: Install 6.0.x
    inputs:
      version: "6.0.x"

  - task: NuGetCommand@2
    displayName: Restore
    inputs:
      restoreSolution: "$(solution)"

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: "build"
      arguments: "$(solution)"

  - task: DotNetCoreCLI@2
    displayName: Test
    inputs:
      command: "test"
      arguments: "$(solution)"

  - task: DotNetCoreCLI@2
    displayName: Publish
    inputs:
      command: publish
      publishWebProjects: true
      arguments: "--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)"
      zipAfterPublish: true

  - task: PublishBuildArtifacts@1
    displayName: "Publish Artifacts: build"
    inputs:
      PathtoPublish: "$(Build.ArtifactStagingDirectory)"
      ArtifactName: "build"
      publishLocation: "Container"
